# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
      
  checkout_code:
    steps:
      - checkout
      - run: echo "Finished checkout code job"
  bundle_dependencies:
    steps:
      - checkout
      - run: echo "Finished bundle_dependencies job"
  something_test:
    steps:
      - checkout
      - run: echo "Finished something test job"
  deploy:
    steps:
      - checkout
      - run: echo "Finished deploy job"
    
 workflows:
  version: 2
  
  build_and_deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - something_test:
          requires:
            - bundle_dependencies:
      - deploy:
          requires:
            - something_test
