# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.0
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "build end"
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "test end"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
